apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: todo
  annotations:
    github.com/project-slug: BenjaminDavison/slopcannon-flask-db-todo
    slopcloud.io/image: ghcr.io/benjamindavison/slopcannon-flask-db-todo-web:latest
    slopcloud.io/ingress-url: http://todo.localhost:8088
spec:
  type: webapp
  lifecycle: experimental
  owner: group:default/guests
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: todo-api
  annotations:
    github.com/project-slug: BenjaminDavison/slopcannon-flask-db-todo
    slopcloud.io/image: ghcr.io/benjamindavison/slopcannon-flask-db-todo-api:latest
    slopcloud.io/ingress-url: http://todo-api.localhost:8088
    slopcloud.io/database: todo-db
spec:
  type: webapp
  lifecycle: experimental
  owner: group:default/guests
  dependsOn:
    - resource:default/todo-db
